namespace AutoCollection;
internal static class Constants
{
	public const string LIST_ATTRIBUTE_NAME = "GenerateListAttribute";
	public const string READ_ONLY_LIST_ATTRIBUTE_NAME = "GenerateReadOnlyListAttribute";
	public const string NAMESPACE_NAME = nameof(AutoCollection);
	public const string COLLECTION_TYPE_PARAMETER_NAME = "collectionType";
	public const string BACKING_FIELD_PARAMETER_NAME = "backingField";
	public const string AUTO_GENERATED_MESSAGE =
		"""
		//--------------------------------------------------------------------------------------------------
		// <auto-generated>
		//     This code was generated by a tool.
		//
		//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
		// </auto-generated>
		//--------------------------------------------------------------------------------------------------
		""";
}
